### Get List
GET http://localhost:3000/db

### Get Item
GET http://localhost:3000/db/gkmaem03u149

### Create Item
POST http://localhost:3000/db
Content-Type: application/json

{
  "title": "Two",
  "content": "Second item"
}

### Update Item
PUT http://localhost:3000/db/30z09zfqqk77
Content-Type: application/json

{
  "completed": true
}

### Delete Item
delete http://localhost:3000/db/ezh7utujx5gn